// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Baytzaki smart-home and art-furniture catalog. Returns matching products with name, price (EGP), brand, slug, and stock.",
  inputSchema: {
    query: z.string().describe("Free-text query matched against product name, brand, and description. Use an empty string to list featured items.").default(""),
    limit: z.number().int().min(1).max(30).default(10).describe("Max results (1-30)."),
    in_stock: z.boolean().default(true).describe("Only return products currently in stock.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, in_stock }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("products").select("id, name, slug, price, original_price, brand, stock, description, image_url").limit(limit);
    if (in_stock) q = q.gt("stock", 0);
    const trimmed = query.trim();
    if (trimmed) {
      const safe = trimmed.replace(/[%,]/g, " ");
      q = q.or(
        `name.ilike.%${safe}%,brand.ilike.%${safe}%,description.ilike.%${safe}%`
      );
    } else {
      q = q.order("created_at", { ascending: false });
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Search failed: ${error.message}` }], isError: true };
    }
    const items = (data ?? []).map((p) => ({
      name: p.name,
      slug: p.slug,
      price_egp: p.price,
      original_price_egp: p.original_price,
      brand: p.brand,
      stock: p.stock,
      url: `/products/${p.slug}`,
      image: p.image_url,
      description: p.description?.slice(0, 300) ?? null
    }));
    return {
      content: [{ type: "text", text: `Found ${items.length} product(s).` }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Look up one Baytzaki product by its slug. Returns full details, price in EGP, stock, and specifications.",
  inputSchema: {
    slug: z2.string().min(1).describe("Product slug (e.g. 'aqara-hub-m2').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("products").select("id, name, slug, price, original_price, brand, stock, description, image_url, images, protocol, specifications, tags").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No product with slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: `${data.name} \u2014 EGP ${data.price}` }],
      structuredContent: { ...data, url: `/products/${data.slug}` }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List the Baytzaki product categories (lighting, security, climate, etc.) with their store URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("categories").select("name, slug, description").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = (data ?? []).map((c) => ({ ...c, url: `/products?category=${c.slug}` }));
    return {
      content: [{ type: "text", text: `${items.length} categories.` }],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
function userClient(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in Baytzaki customer's orders (id, total EGP, status, date).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Sign in required." }], isError: true };
    }
    const { data, error } = await userClient(ctx).from("orders").select("id, total, status, email, created_at, shipping_address").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} order(s).` }],
      structuredContent: { count: data?.length ?? 0, orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-loyalty.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
function userClient2(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_loyalty_default = defineTool5({
  name: "get_my_loyalty",
  title: "Get my loyalty balance",
  description: "Return the signed-in Baytzaki customer's loyalty points balance, lifetime points, and tier (bronze/silver/gold/platinum).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Sign in required." }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No email on this account." }], isError: true };
    }
    const { data, error } = await userClient2(ctx).from("loyalty_points").select("points_balance, lifetime_points, tier").eq("email", email).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = data ?? { points_balance: 0, lifetime_points: 0, tier: "bronze" };
    return {
      content: [{ type: "text", text: `${result.points_balance} points (${result.tier}).` }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vgwptcvjhmphqhoepbri";
var mcp_default = defineMcp({
  name: "baytzaki-mcp",
  title: "Baytzaki",
  version: "0.1.0",
  instructions: "Tools for the Baytzaki Egyptian smart-home and art-furniture store. Use `search_products` and `get_product` to browse the catalog (prices in EGP), `list_categories` for sections, and `list_my_orders` / `get_my_loyalty` for the signed-in customer's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_categories_default, list_my_orders_default, get_my_loyalty_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
